version: "3.5"

services:
  app:
    image: openbookpublishers/readthedocs
    container_name: "readthedocs_app"
    restart: unless-stopped
    volumes:
      - ./local_settings.py:/rtd/readthedocs/settings/local_settings.py:ro
      - ./templates:/var/custom_templates:ro
      - app:/rtd

  proxy:
    image: nginx
    container_name: "readthedocs_proxy"
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - app:/rtd:ro
    depends_on:
      - app

volumes:
  app:
